name: paycor-driver-sync
on: push
jobs:
  codetest:
    name: Codetest
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.0'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache Go's build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache build tools
        id: cachebuildtools
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/go/bin/golangci-lint
            /home/runner/go/bin/govulncheck
          key: ${{ runner.os }}-tools-gol-govuln
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: Install golangci-lint
        if: steps.cachebuildtools.outputs.cache-hit != 'true'
        env:
          GOLANGCI_LINT_VERSION: v1.64.5
        run: |
          sudo curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Install govulncheck
        if: steps.cachebuildtools.outputs.cache-hit != 'true'
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Configure git for private modules
        run: git config --global url."https://${{ secrets.PERSONAL_ACCESS_USERNAME }}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Get dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make get

      - name: Codetest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make codetest
